### ISSUE TITLE
Make new release to publish the content on gh-pages

### ISSUE THREAD

**Issue by JaroCamphuijsen** [NLeSC/internal-training#2]
@AdamBelloum 

You can now publish the page by [making a new release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) of this repository. 

You can also add me to the repository as contributor, then I can do it for you.

**Comment by AdamBelloum** [comment]
@JaroCamphuijsen 

Sorry I took me some time, to comeback to the internal-training, I have created a new release and added you as a contributor

**Comment by JaroCamphuijsen** [comment]
Hi Adam, the problem is solved. The settings for deploying to github pages were not set up in the right way. Under the Settings tab of this repository, in the "pages" setting, the source from which to build the page should have been set to "deploy from branch" and the branch specified to "gh-pages". I'm sorry for the inconvenience. I think this should have been clearer in the documentation. I will make an issue in NEBULA to clarify this as well as the behavior of the baseURL setting in the config file. Thank you for bearing with me. Let me know if you need more help.
